export const BLOG_CACHE = {
  REVALIDATE: 60 * 60 * 24,
  STATIC_CACHE: 60 * 60 * 24 * 7,
  DYNAMIC_CACHE: 60 * 60,
} as const;

export const DISPLAY_SETTINGS = {
  POSTS_PER_PAGE: 12,
  FEATURED_POSTS_COUNT: 1,
  POPULAR_POSTS_COUNT: 3,
  RELATED_POSTS_COUNT: 3,
  RECENT_POSTS_COUNT: 5,
} as const;

export const CONTENT_LIMITS = {
  EXCERPT_LENGTH: 160,
  META_DESCRIPTION_LENGTH: 155,
  TITLE_LENGTH: 60,
  MAX_KEYWORDS: 10,
  MAX_TAGS: 5,
} as const;
